DEBUG:root:received {"dest":"n1","body":{"type":"init","node_id":"n1","node_ids":["n1","n2","n3","n4","n5"],"msg_id":1},"src":"c4","id":4}
INFO:root:node n1 initialized
DEBUG:root:sending {"dest": "c4", "src": "n1", "body": {"msg_id": 1, "in_reply_to": 1, "type": "init_ok"}}
INFO:root:became leader
log
[(('pass', None), 0)]
match index
{'n1': 0, 'n2': 0, 'n3': 0, 'n4': 0, 'n5': 0}

INFO:root:vote ended, new leader is
n1

INFO:root:sending HB

DEBUG:root:sending {"dest": "n2", "src": "n1", "body": {"msg_id": 2, "type": "AppendEntries", "term": 0, "prevIndex": 0, "prevTerm": 0, "entries": [[["pass", null], 0]], "commit": 0}}
DEBUG:root:sending {"dest": "n3", "src": "n1", "body": {"msg_id": 3, "type": "AppendEntries", "term": 0, "prevIndex": 0, "prevTerm": 0, "entries": [[["pass", null], 0]], "commit": 0}}
DEBUG:root:sending {"dest": "n4", "src": "n1", "body": {"msg_id": 4, "type": "AppendEntries", "term": 0, "prevIndex": 0, "prevTerm": 0, "entries": [[["pass", null], 0]], "commit": 0}}
DEBUG:root:sending {"dest": "n5", "src": "n1", "body": {"msg_id": 5, "type": "AppendEntries", "term": 0, "prevIndex": 0, "prevTerm": 0, "entries": [[["pass", null], 0]], "commit": 0}}
DEBUG:root:received {"dest":"n1","src":"n2","body":{"msg_id":2,"in_reply_to":2,"type":"AppendEntriesRes","res":true,"term":0,"next":2,"commit":0},"id":14}
DEBUG:root:received {"dest":"n1","src":"n3","body":{"msg_id":2,"in_reply_to":3,"type":"AppendEntriesRes","res":true,"term":0,"next":2,"commit":0},"id":15}
DEBUG:root:received {"dest":"n1","src":"n4","body":{"msg_id":2,"in_reply_to":4,"type":"AppendEntriesRes","res":true,"term":0,"next":2,"commit":0},"id":16}
DEBUG:root:received {"dest":"n1","src":"n5","body":{"msg_id":2,"in_reply_to":5,"type":"AppendEntriesRes","res":true,"term":0,"next":2,"commit":0},"id":17}
INFO:root:sending HB

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 1371, in run
    self.function(*self.args, **self.kwargs)
  File "/home/peter/Documents/tf/lab3/raft.py", line 128, in recursive_heartbeats
    heartbeat(dest)
  File "/home/peter/Documents/tf/lab3/raft.py", line 117, in heartbeat
    prevTerm=log[nextIndex[dest]-1][1]
IndexError: list index out of range
DEBUG:root:received {"dest":"n1","body":{"key":0,"from":4,"to":3,"type":"cas","msg_id":1},"src":"c13","id":24}
