DEBUG:root:received {"dest":"n1","body":{"type":"init","node_id":"n1","node_ids":["n0","n1","n2","n3"],"msg_id":1},"src":"c1","id":1}
INFO:root:node n1 initialized
DEBUG:root:sending {"dest": "c1", "src": "n1", "body": {"msg_id": 1, "in_reply_to": 1, "type": "init_ok"}}
DEBUG:root:received {"dest":"n1","body":{"txn":[["r",8,null],["r",8,null],["append",8,1]],"type":"txn","msg_id":1},"src":"c8","id":8}
INFO:root:Sending msg to be replicated, destn0
DEBUG:root:sending {"dest": "n0", "src": "n1", "body": {"msg_id": 2, "type": "txnRep", "msg": {"dest": "n1", "body": {"txn": [["r", 8, null], ["r", 8, null], ["append", 8, 1]], "type": "txn", "msg_id": 1}, "src": "c8", "id": 8}, "originalid": 1}}
INFO:root:Sending msg to be replicated, destn2
DEBUG:root:sending {"dest": "n2", "src": "n1", "body": {"msg_id": 3, "type": "txnRep", "msg": {"dest": "n1", "body": {"txn": [["r", 8, null], ["r", 8, null], ["append", 8, 1]], "type": "txn", "msg_id": 1}, "src": "c8", "id": 8}, "originalid": 1}}
INFO:root:Sending msg to be replicated, destn3
DEBUG:root:sending {"dest": "n3", "src": "n1", "body": {"msg_id": 4, "type": "txnRep", "msg": {"dest": "n1", "body": {"txn": [["r", 8, null], ["r", 8, null], ["append", 8, 1]], "type": "txn", "msg_id": 1}, "src": "c8", "id": 8}, "originalid": 1}}
DEBUG:root:received {"dest":"n1","src":"n0","body":{"msg_id":2,"type":"txnRep","msg":{"dest":"n0","body":{"txn":[["r",3,null],["append",9,1]],"type":"txn","msg_id":1},"src":"c9","id":12},"originalid":1},"id":13}
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-4' coro=<handle() done, defined at /home/peter/Documents/tf/lab4/cent.py:57> exception=TypeError("'bool' object is not subscriptable")>
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab4/cent.py", line 82, in handle
    await trycommits(msgQ,db)
  File "/home/peter/Documents/tf/lab4/cent.py", line 46, in trycommits
    msg=item[0]
TypeError: 'bool' object is not subscriptable
DEBUG:root:received {"dest":"n1","src":"n2","body":{"msg_id":3,"type":"txnRep","msg":{"dest":"n2","body":{"txn":[["append",9,2]],"type":"txn","msg_id":1},"src":"c10","id":16},"originalid":1},"id":18}
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-5' coro=<handle() done, defined at /home/peter/Documents/tf/lab4/cent.py:57> exception=TypeError("'bool' object is not subscriptable")>
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab4/cent.py", line 82, in handle
    await trycommits(msgQ,db)
  File "/home/peter/Documents/tf/lab4/cent.py", line 46, in trycommits
    msg=item[0]
TypeError: 'bool' object is not subscriptable
DEBUG:root:received {"dest":"n1","src":"n3","body":{"msg_id":3,"type":"txnRep","msg":{"dest":"n3","body":{"txn":[["append",8,2],["r",8,null]],"type":"txn","msg_id":1},"src":"c11","id":20},"originalid":1},"id":22}
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-6' coro=<handle() done, defined at /home/peter/Documents/tf/lab4/cent.py:57> exception=TypeError("'bool' object is not subscriptable")>
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab4/cent.py", line 82, in handle
    await trycommits(msgQ,db)
  File "/home/peter/Documents/tf/lab4/cent.py", line 46, in trycommits
    msg=item[0]
TypeError: 'bool' object is not subscriptable
