DEBUG:root:received {"dest":"n1","body":{"type":"init","node_id":"n1","node_ids":["n1","n2","n3","n4","n5"],"msg_id":1},"src":"c4","id":4}
INFO:root:node n1 initialized
DEBUG:root:sending {"dest": "c4", "src": "n1", "body": {"msg_id": 1, "in_reply_to": 1, "type": "init_ok"}}
DEBUG:root:sending {"dest": "n1", "src": "n1", "body": {"msg_id": 2, "type": "AppendEntries", "term": 0, "prevIndex": 0, "prevTerm": 0, "entries": [[["pass", null], 0]], "commit": 0}}
DEBUG:root:sending {"dest": "n2", "src": "n1", "body": {"msg_id": 3, "type": "AppendEntries", "term": 0, "prevIndex": 0, "prevTerm": 0, "entries": [[["pass", null], 0]], "commit": 0}}
DEBUG:root:sending {"dest": "n3", "src": "n1", "body": {"msg_id": 4, "type": "AppendEntries", "term": 0, "prevIndex": 0, "prevTerm": 0, "entries": [[["pass", null], 0]], "commit": 0}}
DEBUG:root:sending {"dest": "n4", "src": "n1", "body": {"msg_id": 5, "type": "AppendEntries", "term": 0, "prevIndex": 0, "prevTerm": 0, "entries": [[["pass", null], 0]], "commit": 0}}
DEBUG:root:sending {"dest": "n5", "src": "n1", "body": {"msg_id": 6, "type": "AppendEntries", "term": 0, "prevIndex": 0, "prevTerm": 0, "entries": [[["pass", null], 0]], "commit": 0}}
ERROR:root:fatal exception in handler
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab3/ms.py", line 27, in exitOnError
    fn(*args)
  File "/home/peter/Documents/tf/lab3/raft.py", line 215, in handle
    become_leader()
  File "/home/peter/Documents/tf/lab3/raft.py", line 173, in become_leader
    recursive_heartbeats(node_ids,MIN_HB,MAX_HB)
  File "/home/peter/Documents/tf/lab3/raft.py", line 118, in recursive_heartbeats
    Timer(sec, recursive_heartbeats,dests,min_time,max_time).start()
TypeError: Timer.__init__() takes from 3 to 5 positional arguments but 6 were given
